version: '3.1'
services:
  database:
    image: postgres:14.0
    ports:
      - 5433:5432
    command: postgres -c log_statement=all -c timezone='America/Mexico_City'
    volumes:
      - ./postgres-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 4201:4200
    depends_on:
      - backend
